-- uriPos Supabase schema
-- Chay file nay trong Supabase SQL Editor.

create extension if not exists pgcrypto;

grant usage on schema public to anon, authenticated;

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  avatar text not null default '',
  is_online boolean not null default false,
  last_seen_at timestamptz,
  offline_since timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id bigint not null references public.admin_users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table if not exists public.content_structures (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_fields (
  id bigint generated by default as identity primary key,
  content_structure_id bigint not null references public.content_structures(id) on delete cascade,
  name text not null,
  slug text not null,
  type text not null default 'single_line',
  required boolean not null default false,
  description text not null default '',
  options jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (content_structure_id, slug)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  thumbnail text not null default '',
  content_structure_id bigint references public.content_structures(id) on delete set null,
  price numeric(12,2) not null default 0,
  quantity integer not null default 0,
  short_desc text not null default '',
  publish boolean not null default false,
  field_values jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_media (
  id bigint generated by default as identity primary key,
  url text not null,
  bucket text not null default 'app-media',
  path text not null unique,
  file_name text not null default '',
  mime_type text not null default '',
  size bigint not null default 0,
  created_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.discount_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null default 'percent' check (type in ('percent', 'fixed')),
  value numeric(12,2) not null default 0,
  min_subtotal numeric(12,2) not null default 0,
  max_discount numeric(12,2),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  address text not null default '',
  avatar text not null default '',
  loyalty_points integer not null default 0,
  rank text not null default 'Thanh vien',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  theme text not null default 'light',
  logo_url text not null default '',
  logo_text text not null default 'A',
  brand_name text not null default 'APOS PANEL',
  font_family text not null default 'Inter',
  font_sizes jsonb not null default '{"h1":34,"h2":28,"h3":24,"h4":20,"h5":17,"h6":15}'::jsonb,
  sidebar_color text not null default 'dark',
  sidebar_custom_from text not null default '#1C1C1E',
  sidebar_custom_to text not null default '#1C1C1E',
  sidebar_active_color text not null default '#16A34A',
  accent_color text not null default '#16A34A',
  border_radius text not null default 'md',
  customer_rank_rules jsonb not null default '[{"name":"Thanh vien","min_points":0},{"name":"Bac","min_points":100},{"name":"Vang","min_points":300},{"name":"Kim cuong","min_points":700}]'::jsonb,
  point_exchange_amount integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_settings (
  id bigint generated by default as identity primary key,
  bank_name text not null default '',
  account_name text not null default '',
  account_number text not null default '',
  qr_image text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null default '',
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null default 'Khach le',
  staff_id bigint references public.admin_users(id) on delete set null,
  note text not null default '',
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  paid_amount numeric(12,2) not null default 0,
  due_amount numeric(12,2) not null default 0,
  payment_method text not null default 'cash',
  payment_status text not null default 'unpaid',
  cash_received numeric(12,2) not null default 0,
  change_amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null default '',
  sku text not null default '',
  qty integer not null default 1,
  price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  message text not null,
  type text not null default 'info',
  recipient_type text not null default 'all',
  recipient_ids jsonb not null default '[]'::jsonb,
  created_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_receipts (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.notifications(id) on delete cascade,
  user_id bigint not null references public.admin_users(id) on delete cascade,
  is_read boolean not null default false,
  read_at timestamptz,
  is_liked boolean not null default false,
  liked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (notification_id, user_id)
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  customer_id bigint not null unique references public.customers(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_type text not null check (sender_type in ('user', 'customer')),
  sender_user_id bigint references public.admin_users(id) on delete set null,
  sender_customer_id bigint references public.customers(id) on delete set null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, product_id)
);

grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;

alter table public.permissions disable row level security;
alter table public.roles disable row level security;
alter table public.role_permissions disable row level security;
alter table public.admin_users disable row level security;
alter table public.user_roles disable row level security;
alter table public.content_structures disable row level security;
alter table public.content_fields disable row level security;
alter table public.products disable row level security;
alter table public.product_media disable row level security;
alter table public.discount_codes disable row level security;
alter table public.customers disable row level security;
alter table public.app_settings disable row level security;
alter table public.payment_settings disable row level security;
alter table public.orders disable row level security;
alter table public.order_items disable row level security;
alter table public.notifications disable row level security;
alter table public.notification_receipts disable row level security;
alter table public.conversations disable row level security;
alter table public.messages disable row level security;
alter table public.cart_items disable row level security;

insert into public.permissions (name)
select unnest(array[
  'dashboard.view',
  'pos.access',
  'order.view',
  'order.create',
  'order.update',
  'order.delete',
  'product.view',
  'product.create',
  'product.update',
  'product.delete',
  'customer.view',
  'customer.create',
  'customer.update',
  'customer.delete',
  'discount.view',
  'discount.create',
  'discount.update',
  'discount.delete',
  'chat.view',
  'chat.reply',
  'chat.delete',
  'notification.view',
  'notification.create',
  'notification.update',
  'notification.delete',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'payment.view',
  'payment.update',
  'user.view',
  'user.create',
  'user.update',
  'user.delete',
  'role.view',
  'role.create',
  'role.update',
  'role.delete'
]::text[])
on conflict (name) do nothing;

insert into public.roles (name)
values ('Owner'), ('Manager'), ('Staff')
on conflict (name) do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on true
where r.name = 'Owner'
on conflict (role_id, permission_id) do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.name = any (array[
  'dashboard.view',
  'pos.access',
  'order.view',
  'order.create',
  'order.update',
  'product.view',
  'product.create',
  'product.update',
  'customer.view',
  'customer.create',
  'customer.update',
  'discount.view',
  'discount.create',
  'discount.update',
  'chat.view',
  'chat.reply',
  'notification.view',
  'notification.create',
  'notification.update',
  'content.view',
  'content.create',
  'content.update',
  'payment.view',
  'payment.update'
]::text[])
where r.name = 'Manager'
on conflict (role_id, permission_id) do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.name = any (array[
  'dashboard.view',
  'pos.access',
  'order.view',
  'order.create',
  'product.view',
  'customer.view',
  'customer.create',
  'chat.view',
  'chat.reply',
  'notification.view'
]::text[])
where r.name = 'Staff'
on conflict (role_id, permission_id) do nothing;

insert into public.admin_users (
  name,
  email,
  password_hash,
  is_online,
  offline_since
)
values (
  'Administrator',
  'hoanganmsc@gmail.com',
  '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
  false,
  now()
)
on conflict (email) do update
set
  name = excluded.name,
  password_hash = excluded.password_hash,
  updated_at = now();

insert into public.user_roles (user_id, role_id)
select u.id, r.id
from public.admin_users u
join public.roles r on r.name = 'Owner'
where u.email = 'hoanganmsc@gmail.com'
on conflict (user_id, role_id) do nothing;

insert into public.app_settings (
  theme,
  logo_url,
  logo_text,
  brand_name,
  font_family,
  font_sizes,
  sidebar_color,
  sidebar_custom_from,
  sidebar_custom_to,
  sidebar_active_color,
  accent_color,
  border_radius,
  customer_rank_rules,
  point_exchange_amount
)
select
  'light',
  '',
  'A',
  'APOS PANEL',
  'Inter',
  '{"h1":34,"h2":28,"h3":24,"h4":20,"h5":17,"h6":15}'::jsonb,
  'dark',
  '#1C1C1E',
  '#1C1C1E',
  '#16A34A',
  '#16A34A',
  'md',
  '[{"name":"Thanh vien","min_points":0},{"name":"Bac","min_points":100},{"name":"Vang","min_points":300},{"name":"Kim cuong","min_points":700}]'::jsonb,
  1000
where not exists (select 1 from public.app_settings);

insert into public.payment_settings (
  bank_name,
  account_name,
  account_number,
  qr_image
)
select '', '', '', ''
where not exists (select 1 from public.payment_settings);

insert into storage.buckets (id, name, public)
values ('app-media', 'app-media', true)
on conflict (id) do update
set public = excluded.public;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public read app-media'
  ) then
    create policy "Public read app-media"
      on storage.objects
      for select
      to public
      using (bucket_id = 'app-media');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public insert app-media'
  ) then
    create policy "Public insert app-media"
      on storage.objects
      for insert
      to public
      with check (bucket_id = 'app-media');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public update app-media'
  ) then
    create policy "Public update app-media"
      on storage.objects
      for update
      to public
      using (bucket_id = 'app-media')
      with check (bucket_id = 'app-media');
  end if;
end $$;
